name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        ros_distro: [melodic, noetic]

    runs-on: ubuntu-latest
    container: osrf/ros:${{ matrix.ros_distro }}-desktop
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -qy g++ libeigen3-dev
          rosdep update
          rosdep install --from-paths . --ignore-src -y -r --as-root apt:false

      - name: Setup catkin workspace
        run: |
          . /opt/ros/${{ matrix.ros_distro }}/setup.sh
          mkdir -p ${RUNNER_WORKSPACE}/catkin_ws/src
          cd ${RUNNER_WORKSPACE}/catkin_ws/src
          ln -s ${GITHUB_WORKSPACE}
          catkin_init_workspace .

      - name: Build workspace
        run: |
          . /opt/ros/${{ matrix.ros_distro }}/setup.sh
          cd ${RUNNER_WORKSPACE}/catkin_ws
          export LDFLAGS="-Wl,-O1,--sort-common,--as-needed,--no-undefined,-z,relro,-z,now -pthread"
          catkin_make -DCMAKE_BUILD_TYPE=NONE
